name = "valmark-website"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "INQUIRIES"
id = "<REPLACE_AFTER_CREATING_NAMESPACE>"
